# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format --include
        types_or: ["c#"]
