name: Pre-Commit

on:
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: pre-commit-ci-lite
      uses: pre-commit-ci/lite-action@v1.0.0
      if: always()
