name: Pre-Commit

on:
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.x
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Install dotnet-format and restore
      run: |
        dotnet tool install -g dotnet-format
        dotnet workload restore
        dotnet restore
      shell: bash

    - name: pre-commit-ci-lite
      uses: pre-commit-ci/lite-action@v1.0.0
      if: always()
