name: Pre-Commit

on:
  pull_request:
    branches:
      - dev

jobs:
  format:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          $commitMessage = git log -1 --pretty=format:%s
          if ($commitMessage.Contains("[pre-commit.ci lite]")) {
            Write-Host "Commit message contains [pre-commit.ci lite], exiting workflow."
            exit 0
          }
      - uses: actions/setup-python@v4.7.1
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
