name: Pre-Commit

on:
  pull_request:
    branches:
      - dev

jobs:
  format:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - run: dotnet restore
      - uses: actions/setup-python@v4.7.1
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
        with:
          msg: "[skip ci] [pre-commit.ci lite] apply automatic fixes"
