name: Pre-Commit

on:
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
